// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"github.com/movex-dev/movie-server/domain/config"
	"net/http"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from wire.go:

func InitMuxServer(ctx context.Context, cfg *config.Vars) (*MuxServer, func(), error) {
	database := cfg.Database
	client, err := entClientProvider(database)
	if err != nil {
		return nil, nil, err
	}
	serveMux := newMux(cfg, client)
	muxServer := &MuxServer{
		Mux: serveMux,
	}
	return muxServer, func() {
	}, nil
}

// wire.go:

type MuxServer struct {
	Mux *http.ServeMux
}
