version: 3
endpoint: http://localhost:5111
admin_secret: admin_secret
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
