version: '3.6'
services:
  postgres:
    container_name: movie-hasura-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: movex
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movex"]
      interval: 10s
      timeout: 5s
      retries: 5

  graphql-engine:
    container_name: hasura-movie-graphql-engine-1
    image: hasura/graphql-engine:latest
    ports:
      - "5111:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/movex
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/movex
      HASURA_GRAPHQL_LOG_LEVEL: debug

volumes:
  db_data: