// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// VideosColumns holds the columns for the "videos" table.
	VideosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
	}
	// VideosTable holds the schema information for the "videos" table.
	VideosTable = &schema.Table{
		Name:       "videos",
		Columns:    VideosColumns,
		PrimaryKey: []*schema.Column{VideosColumns[0]},
	}
	// VideoVideosColumns holds the columns for the "video_videos" table.
	VideoVideosColumns = []*schema.Column{
		{Name: "video_id", Type: field.TypeInt},
		{Name: "video_id", Type: field.TypeInt},
	}
	// VideoVideosTable holds the schema information for the "video_videos" table.
	VideoVideosTable = &schema.Table{
		Name:       "video_videos",
		Columns:    VideoVideosColumns,
		PrimaryKey: []*schema.Column{VideoVideosColumns[0], VideoVideosColumns[1], VideoVideosColumns[0], VideoVideosColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "video_videos_video_id",
				Columns:    []*schema.Column{VideoVideosColumns[0], VideoVideosColumns[1]},
				RefColumns: []*schema.Column{VideosColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "video_videos_video_id",
				Columns:    []*schema.Column{VideoVideosColumns[0], VideoVideosColumns[1]},
				RefColumns: []*schema.Column{VideosColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		VideosTable,
		VideoVideosTable,
	}
)

func init() {
	VideoVideosTable.ForeignKeys[0].RefTable = VideosTable
	VideoVideosTable.ForeignKeys[1].RefTable = VideosTable
}
