// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/movex-dev/movie-server/infrastructure/ent/schema"
	"github.com/movex-dev/movie-server/infrastructure/ent/video"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	videoFields := schema.Video{}.Fields()
	_ = videoFields
	// videoDescTitle is the schema descriptor for title field.
	videoDescTitle := videoFields[0].Descriptor()
	// video.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	video.TitleValidator = videoDescTitle.Validators[0].(func(string) error)
	// videoDescDescription is the schema descriptor for description field.
	videoDescDescription := videoFields[1].Descriptor()
	// video.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	video.DescriptionValidator = videoDescDescription.Validators[0].(func(string) error)
	// videoDescURL is the schema descriptor for url field.
	videoDescURL := videoFields[2].Descriptor()
	// video.URLValidator is a validator for the "url" field. It is called by the builders before save.
	video.URLValidator = videoDescURL.Validators[0].(func(string) error)
}
